### ISSUE TITLE
Bot is inactive and won't respond

### ISSUE THREAD

**Issue by ghost** [eggsywashere/discord-steam-verification#19]
yes I have read the readme, and the issues already posted, followed them exactly, my bot will come online, but it won't respond to anything and gives me no errors.

**Comment by eggsy** [comment]
Hey @Radix-Comet,

Thank you for letting me know. I haven't been quite working on this project and Discord bots for a while. I found the issue and it's due to Discord's regulations a.k.a. intents for bots. You have to enable the following setting in your bot's page in Developer Portal. Then, it might work. If not, I am going to release an update with bunch of fixes, upgrades and improvements which means you can clone the repo again for a fixed version. Stay tuned!

<img width="658" alt="image" src="https://user-images.githubusercontent.com/13917975/222978986-96902f95-4775-48a3-8b3e-67b6e0671be8.png">

**Comment by eggsy** [comment]
Closing this issue as it seems to be working fine.
